version: "3.9"
services:
  rosys:
    image: "zauberzeug/rosys:latest"
    volumes:
      - ./:/app
      - ~/.rosys:/root/.rosys
      - ./../rosys:/rosys
      - ./../nicegui/nicegui:/usr/local/lib/python3.11/site-packages/nicegui
      - ~/data:/data
    network_mode: host
    restart: always
    privileged: true
    environment:
      - ROBOT_ID=Field Friend
      - TZ=Europe/Amsterdam
    hostname: docker
    cap_add:
      - SYS_NICE # allow container to set process priorities
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "100"
    command: /start.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  detector:
    image: "zauberzeug/yolov5-detector:32.6.1"
    restart: always
    ports:
      - "8004:80"
    hostname: ${ROBOT_ID}
    environment:
      - HOST=learning-loop.ai
      - ORGANIZATION=zauberzeug
      - PROJECT=coins
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/data:/data
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "curl",
    #       "-f",
    #       "-X POST",
    #       "-F 'file=@/usr/local/lib/python3.6/dist-packages/learning_loop_node/detector/tests/test.jpg'",
    #       "-H 'mac: FF:FF:FF:FF:FF'",
    #       "localhost/detect",
    #       "|| exit 1",
    #     ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 500s
