version: "3.9"
services:
  rosys:
    image: "zauberzeug/rosys:latest"
    volumes:
      - ./:/app
      - ./../rosys:/rosys # TODO remove this when rosys is published with https://github.com/zauberzeug/rosys/pull/16
      - ~/.rosys:/root/.rosys
      - ~/data:/data
    network_mode: host
    restart: always
    privileged: true
    environment:
      - ROBOT_ID
      - TZ=Europe/Amsterdam
    hostname: docker
    cap_add:
      - SYS_NICE # allow container to set process priorities
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "100"
    command: /start.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
